Feature mdr 49 contact us
JMSevilla/mdr-fe-ts-v2 pull request #33
Opened 2023-05-23 02:40 UTC by labaynecss

2023-05-23 02:59 UTC, acostales08 approved these changes

2023-05-23 03:32 UTC, JMSevilla requested changes

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +  const methods = useForm({
change from "methods" to "form"

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +        <Grid container spacing={2}>
Use our built in component "ControlledGrid"

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +              control={methods.control}
do not use "method.control" instead use "control" only

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +const ContactForm = () => {
Your code is too straight forward. Isolate your grid and textfield to different function example.

Also you should consider using 

- useFormContext inside your ContactUsForm

const ContactUsForm = () => {
//...here you can put the Grid and ControlledTextField
}


export const ContactUs = () => {
const form = useForm({})
return (
<FormProvider {...form}></FormProvider>
)
}

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +              control={methods.control}
Also when implementing ControlledTextField , there must be required , shouldUnregister

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +                <Checkbox
we have a component for checkbox named "ControlledCheckbox"

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +                  {...methods.register('tms')}
we shouldn't use ...methods.register. we are just using control={control}

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactForm.tsx
> +              onClick={methods.handleSubmit(onSubmit)}
from "methods.handleSubmit" must be onClick={handleContinue}

const handleContinue = () => {
handleSubmit((values) => {}) return false
}

2023-05-23 03:32 UTC, JMSevilla commented on src/components/Content/contactUs/ContactUsContent.tsx
> +const ContactUs: React.FC<ContactUsProps> = ({ children }) => {
Don't create ContactUsProps and implement here. 

Instead use "React.PropsWithChildren<{}>"

2023-05-23 03:32 UTC, JMSevilla commented on src/pages/contactUs.tsx
> +        children={
We are now preventing this code we are just not yet doing some migration to this. 

If your component is expecting a children react node. then use 

<ContactUs>
//...your design here
</ContactUs>

2023-06-10 06:32 UTC, acostales08 reviewed
wrong file

2023-07-17 05:28 UTC, closed without merging